HW_11/HW_11/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('app1.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HW_11/app1/urls.py
from django.urls import path
from .views import *

app_name = "app1"
urlpatterns = [
    path('', index, name='index'),
    path('students/', StudentsView.as_view(), name='students'),
    path('students/<slug:name_slug>/', StudentView.as_view(), name='student'),
]

HW_11/users/urls.py
from django.urls import path, include
from . import views
# from .views import logout_view


app_name = "users"
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    # path('logout/', logout_view, name='logout'),
]

HW_11/app1/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse

# Create your models here.

class Student(models.Model):
    name = models.CharField(
        max_length=30,
        verbose_name='Имя',
        null=False,
        blank=False)

    surname = models.CharField(
        max_length=30,
        verbose_name='Фамилия')

    age = models.SmallIntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(18), MaxValueValidator(99)],
        verbose_name="Возраст")

    sex = models.CharField(
        max_length=10,
        choices=[('m', 'Мужчина'), ('f', 'Женщина')],
        verbose_name='Пол')

    active = models.BooleanField(verbose_name="Активный")

    photo = models.ImageField(
        upload_to=r'phontos/%Y/%m/%d',
        blank=True,
        verbose_name="Фото"
    )

    course = models.ManyToManyField(
        to='Course',
        blank=True,
        verbose_name="Посещаемые курсы")

    slug = models.SlugField(
        max_length=255,
        unique=True,
        db_index=True,
        verbose_name="URL",
        help_text="только латинские",
        default='',)

    time_create = models.DateTimeField(
        null=True,
        auto_now_add=True,
        verbose_name="Время создания")

    time_update = models.DateTimeField(
        null=True,
        auto_now=True,
        verbose_name="Время изменения")


    def __str__(self):
        return f"{self.name} {self.surname} ({self.age})"

    def get_absolute_url(self):
        return reverse('student', kwargs={"name_slug": self.slug})

    class Meta:
        verbose_name = "Студент"
        verbose_name_plural = "Студенты"
        indexes = [models.Index(fields=['surname'])]
        unique_together = [['name', 'surname']]
        ordering = ["surname"]

class Course(models.Model):
    langs = [
        ('py','Python'),
        ('js','JavaScript'),
        ('c','C++'),
        ('an','Android'),
    ]

    name = models.CharField(choices=langs, max_length=20, verbose_name="Курс")
    course_num = models.SmallIntegerField(
        default=1,
        verbose_name="Номер курса",
        validators=[MinValueValidator(1), MaxValueValidator(100)])
    start_date = models.DateField(verbose_name='Начало курса', null=True)
    end_date = models.DateField(verbose_name='Окончание курса', null=True)
    description = models.TextField(blank=True, verbose_name="Описание")

    def __str__(self):
        return f"{self.get_name_display()} - {self.course_num}"

    class Meta:
        unique_together = [['name', 'course_num']]
        verbose_name = "Курс"
        verbose_name_plural = "Курсы"
        ordering = ['name', 'course_num']


class Grade(models.Model):
    person = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        related_name="grades",
        verbose_name='Чья оценка')

    grade = models.PositiveSmallIntegerField(
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        verbose_name='Оценка'
    )

    course = models.ForeignKey(
        Course,
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Курс')

    date = models.DateField(verbose_name='Дата оценки', null=True)

    date_add = models.DateField(
        auto_now_add=True,
        null=True,
        verbose_name='Дата добавления')

    date_update = models.DateField(
        auto_now=True,
        null=True,
        verbose_name='Дата изменения')

    class Meta:
        verbose_name = "Оценка"
        verbose_name_plural = "Оценки"

HW_11/users/models.py
from django.db import models

# Create your models here.

HW_11/app1/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, DetailView
from .models import Student
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

menu =  [
    {'menu1':"url1"},
    {'menu2':"url2"},
]

def index(r):
    return render(r, 'index.html')


class StudentsView(ListView):
    model = Student
    template_name = 'students.html'
    context_object_name = 'students'

    def get(self, r, *args, **kwargs):
        f = r.GET.get('f', default='')
        students = Student.objects.filter(name__contains=f).all()
        return render(r, self.template_name, context={'students': students, 'menu': menu})


class StudentView(LoginRequiredMixin, DetailView):
    model = Student
    template_name = 'student.html'
    slug_url_kwarg = 'name_slug'
    context_object_name = 'student'
    login_url = '/users/login/'

HW_11/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

# def logout_view(request):
#     logout(request)
#     return redirect('app1:index')

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('app1:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

HW_11/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app1/css/index.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
</head>
<body>
    {% block menu %}

    {% endblock %}
    <main class="img-main">
        <section class="img-main-wrap">
            <div>
                {% block content1 %}

                {% endblock %}
            </div>
        </section>
    </main>
    <footer class="footer">
        <div class="conteiner">
            <div class="footer-wrap">
                    <p class="footer-list-item-text">&copy; 2025 Your Company Name. All rights reserved.</p>
                    <ul class="footer-list">
                        <li class="footer-list-item">
                            <a href="#">Privacy Policy</a>
                        </li>
                        <li class="footer-list-item">
                            <a href="#">Terms of Service</a>
                        </li>
                    </ul>
            </div>
        </div>
    </footer>

</body>

</html>

HW_11/templates/index.html
{% extends 'base.html' %}
{% block menu %}
    <header class="header">
        <div class="conteiner">
          <div class="header-wrap">
            <div class="logo-wrap">
              <p class="logo">MAIN PAGE</p>
            </div>
              <nav class="nav-wrap">
                  <ul class="nav-list">
                    <li class="nav-list-item">
                      <a href="/students/"> STUDENTS </a>
                    </li >
                    <li class="nav-list-item">
                      <a href="/admin/"> ADMIN PANEL </a>
                    </li>
                    {% if user.is_authenticated %}
                        <div class="nav-list-item-text">
                            <p>Hello, {{ user.username }}</p>
                        </div>
                        <li class="nav-list-item">
<!--                            <a href="/users/logout/"> LOG out </a>-->
                            <a href="{% url 'users:logout' %}"> LOG OUT </a>
                        </li>
                    {% else %}
                        <li class="nav-list-item">
<!--                            <a href="/users/login/"> LOG IN </a>-->
                            <a href="{% url 'users:login' %}"> LOG IN </a>
                        </li>
                    {% endif %}
                  </ul>
              </nav>
          </div>
        </div>
    </header>
{% endblock %}

HW_11/templates/student.html
{% extends 'base.html' %}
{% load static %}
{% block menu %}
    <header class="header">
        <div class="conteiner">
          <div class="header-wrap">
            <div class="logo-wrap">
              <p class="logo">MAIN PAGE</p>
            </div>
              <nav class="nav-wrap">
                  <ul class="nav-list">
                    <li class="nav-list-item">
                      <a href="/"> MAIN PAGE </a>
                    </li>
                    <li class="nav-list-item">
                      <a href="/admin/"> ADMIN PANEL </a>
                    </li>
                  </ul>
              </nav>
          </div>
        </div>
    </header>
{% endblock %}
{% block content1 %}
<div class="conteiner">
    <div class="st-info">
        <div class="photo">
            {% if student.photo %}
                <img class="st-photo" src="{{student.photo.url}}" alt='Нет ФОТО'>
            {% else %}
                <img class="st-photo" src="{% static 'app1/pic/no-photo.png' %}" alt='Нет ФОТО'>
            {% endif %}
        </div>
        <div class="info">
            <p> Фамилия: {{ student.surname }}</p>
            <p> Имя: {{ student.name }}</p>
            <p> Возраст: {{ student.age }}</p>
            <p> Курсы:
                {% for c in student.course.all %}
                    {{c}}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
        </div>
    </div>
</div>
{% endblock %}

HW_11/templates/students.html
{% extends 'base.html' %}
{% block menu %}
    <header class="header">
        <div class="conteiner">
          <div class="header-wrap">
            <div class="logo-wrap">
              <p class="logo">MAIN PAGE</p>
            </div>
              <nav class="nav-wrap">
                  <ul class="nav-list">
                    <li class="nav-list-item">
                      <a href="/"> MAIN PAGE </a>
                    </li>
                    <li class="nav-list-item">
                      <a href="/admin/"> ADMIN PANEL </a>
                    </li>
                    <li class="nav-list-item">
                      <a href="/users/login/"> LOG IN </a>
                    </li>
                  </ul>
              </nav>
          </div>
        </div>
    </header>
{% endblock %}
{% block content1 %}
<div class="conteiner">
    <table class="students">
        <thead>
            <tr>
                <th>№</th>
                <th>ФИО</th>
                <th>Возраст</th>
                <th>Пол</th>
                <th>ФОТО</th>
            </tr>
        </thead>
        <tbody>
            {% for s in students %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'app1:student' s.slug %}">{{ s.name }} {{ s.surname }}</a></td>
                <td>{{ s.age }}</td>
                <td>{{ s.get_sex_display }}</td>
                <td>
                {% if s.photo %}
                    <img class="img-student thumb" src="{{ s.photo.url }}" alt="Нету">
                {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">List of students is empty</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}